// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  work_experience: dynamic(() => import("./WorkExperience")),
};
